import Head from 'next/head';
import { Articles } from '~/components/Articles';
import { getItems } from '~/fetches/server/qiita';
import { ArticleType } from '~/types/article';

type Props = {
  articles: ArticleType[];
};

export default function Home({ articles }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Articles articles={articles} />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const articles = await getItems({ username: 'ozaki25' });
  return { props: { articles } };
};
